### ISSUE TITLE
PInvokeStackImbalance

### ISSUE THREAD

**Issue by AlucardNosferatu** [AlucardNosferatu/Live2D_DLL_Test#1]
However, when I choose to ignore error prompt, the program runs normally...
I think it must be inproper calling of Live2D.dll possibly the dllimport part misdefined the function input params...but I've checked pattern code of a caller Program, the definition of mine and pattern are the same...

**Comment by Linklelo** [comment]
遇到了同样的问题，找了下解决办法
可以在dllimport中加入CallingConvention参数，就像这样
[DllImport("Live2D.dll", EntryPoint = "StartMotion", CallingConvention = CallingConvention.Cdecl)]

**Comment by AlucardNosferatu** [comment]
> 遇到了同样的问题，找了下解决办法
> 可以在dllimport中加入CallingConvention参数，就像这样
> [DllImport("Live2D.dll", EntryPoint = "StartMotion", CallingConvention = CallingConvention.Cdecl)]

大哥牛逼！解决了！感激不尽！
